
-- Create the storebytes user with a secure password
CREATE USER storebytes WITH PASSWORD 'enter-password-here';

GRANT CONNECT ON DATABASE storebytesdb TO storebytes;
GRANT USAGE ON SCHEMA public TO storebytes;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO storebytes;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO storebytes;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO storebytes;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO storebytes;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO storebytes;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO storebytes;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO storebytes;
REVOKE CONNECT ON DATABASE postgres FROM storebytes;
